name: docscan_design_system
description: "Design tokens, themes and shared widgets."
publish_to: none
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  docscan_core:
    path: ../core
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
